[priority] fix issues with dev mode activator;
Also, update .gitignore and README.md

diff --git a/lib/backend/activate_dev_mode b/lib/backend/activate_dev_mode
--- a/lib/backend/activate_dev_mode
+++ b/lib/backend/activate_dev_mode
@@ -1,17 +1,9 @@
 #!/bin/bash
 
 # Usage:
-# $ . ./activate_dev_mode 
+# $ . ./activate_dev_mode
 # or
-# $ source ./activate_dev_mode 
-
-# user_interrupt(){
-#     echo -e "\n\nKeyboard Interrupt detected."
-#     exit
-# }
-
-# trap user_interrupt SIGINT
-# trap user_interrupt SIGTSTP
+# $ source ./activate_dev_mode
 
 cd ../../
 
@@ -44,27 +36,43 @@ number_of_shards = 5
 number_of_replicas = 1
 
 [Grafana]
-dashboard_url = 0.0.0.0:3000
-api_url = http://0.0.0.0:5000/
+dashboard_url = http://0.0.0.0:3000
+api_url = http://0.0.0.0:5000/db/create/
 ' > conf/sar-index.cfg
 fi
 
 # sed 's/DEBUG = False/DEBUG = True/g' src/config.py
 
-# sed -i -e '/^DEBUG/ s/^#*/# /' src/config.py 
-# sed -i -e '/^CFG_PATH/ s/^#*/# /' src/config.py 
+# sed -i -e '/^DEBUG/ s/^#*/# /' src/config.py
+# sed -i -e '/^CFG_PATH/ s/^#*/# /' src/config.py
 
 echo 'DEBUG = True' > src/config_local.py
 echo 'CFG_PATH = "'$(realpath conf/sar-index.cfg)'"' >> src/config_local.py
 
-packages_count=$(rpm -q python3-devel gpgme-devel gpgme | wc -l)
-if [[ ! $packages_count -eq 3 ]]; then
-    echo "Need sudo permission for installing python3 devel and gpgme/devel packages"
-    sudo dnf -y install python3-devel gpgme-devel gpgme
+OS_RELEASE=$(lsb_release -i | awk '{print $NF}')
+# OTHER_CMD=$(which <other installer>)
+
+if [[ $OS_RELEASE == 'Fedora' ]]; then
+    packages_count=$(rpm -q python3-devel gpgme-devel gpgme | wc -l)
+    if [[ ! $packages_count -eq 3 ]]; then
+        echo "Need sudo permission for installing python3 devel and gpgme/devel packages"
+        sudo dnf -y install python3-devel gpgme-devel gpgme
+    fi
+elif [[ $OS_RELEASE == 'Ubuntu' ]]; then
+    packages_status=$(dpkg -l libgpgme11 libgpgme11-dev python3-dev | grep 'no packages found')
+    if [[ ! -z $packages_status ]]; then
+        echo "Need sudo permission for installing python3 devel and gpgme/devel packages"
+        sudo apt-get install -y install libgpgme11 libgpgme11-dev python3-gpgme python3-dev
+    fi
+else
+    echo "error can't install a few packages."
+    echo "kindly edit this script to add your package manager in 'OTHER_CMD='"
+    exit 1;
 fi
 
+
 host_status=$(grep '0.0.0.0 redis' /etc/hosts)
-if [[ -z $host_status ]]; then 
+if [[ -z $host_status ]]; then
     echo "Need sudo to append 0.0.0.0 -- redis to /etc/hosts"
     echo '0.0.0.0 redis' | sudo tee -a /etc/hosts
 fi
@@ -73,7 +81,7 @@ export VOS_CONFIG_PATH="$(realpath conf/sar-index.cfg)"
 
 cd src/
 
-if [ ! -d venv/ ]; then 
+if [ ! -d venv/ ]; then
     virtualenv -p python3 venv
     source venv/bin/activate
     pip install -r requirements.txt
