compose overhaul; hooaah. Also: 	- fix metadata creation service 	- move vizit to utils/

diff --git a/lib/middleware/scripts/es-metadata-handler b/lib/middleware/scripts/es-metadata-handler
--- a/lib/middleware/scripts/es-metadata-handler
+++ b/lib/middleware/scripts/es-metadata-handler
@@ -1,8 +1,12 @@
 #!/bin/bash
 
+log(){
+  echo -e "[$(date +'%D %H:%M:%S %Z')] - $*"
+}
+
 user_interrupt(){
-    echo -e "\n\nKeyboard Interrupt detected."
-    echo -e "Stopping Task Manager..."
+    log "\n\nKeyboard Interrupt detected."
+    log "Stopping Task Manager..."
     exit
 }
 
@@ -10,7 +14,7 @@ trap user_interrupt SIGINT
 trap user_interrupt SIGTSTP
 
 start_daemon() {
-    echo "$(date +'%D %H:%M:%S %Z') - starting daemon.."
+    log "starting daemon.."
     ES_HOST=$(egrep '^(host)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
     ES_PORT=$(egrep '^(port)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
     ES_PROTOCOL=$(egrep '^(protocol)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
@@ -19,13 +23,24 @@ start_daemon() {
     	if [[ ! -z $status ]]; then
           /scripts/create_datasource
           if [ $? -eq 0 ]; then
-            echo "$(date +'%D %H:%M:%S %Z') - created datasource.."
+            log "Created datasource for Grafana."
             sleep 1
             systemctl restart api_engine
           else
-            echo "$(date +'%D %H:%M:%S %Z') - index template creation for sarjitsu failed."
+            log "Grafana's datasource creation failed!"
             exit -1
           fi
+
+          log "Attempting to create Index template in Elasticsearch"
+          log "This might take 5-10 multiple attempts.."
+          /scripts/es-create-sarjitsu-templates
+          if [ ! $? -eq 0 ]; then
+            log "ES index template creation for sarjitsu failed!"
+            exit -1
+          else
+            log "ES index template created."
+          fi
+          
     	    break
     	else
     	    echo "$(date +'%D %H:%M:%S %Z') - unable to contact Elasticsearch; sleeping for 2 secs"
